# Generated by Django 3.0 on 2019-12-17 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('phone_num', models.IntegerField(default='079 xxxx xx')),
                ('health_prob', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vistis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2019, 12, 17, 13, 10, 1, 652224))),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField(blank=True, null=True)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=datetime.datetime(2019, 12, 17, 13, 10, 1, 651274))),
                ('to_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.UserInfo')),
            ],
        ),
    ]
