# Generated by Django 3.0 on 2019-12-17 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistis',
            name='to_date',
            field=models.ForeignKey(default=1988, on_delete=django.db.models.deletion.PROTECT, to='mainapp.Subscription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 17, 13, 21, 12, 731564)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2019, 12, 17, 13, 21, 12, 731614)),
        ),
        migrations.AlterField(
            model_name='vistis',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 13, 21, 12, 732718)),
        ),
    ]
